pipeline:
  name: digercic_etl_cedulados
  description: Extraccion de VM_CONTROLES_NINOS_GESTANTES
  version: "1.0.0"
  parallel: false

extractions:
  - name: cedulados_msp
    source: oracle
    config:
      host: ${ORACLE_HOST_MSP}
      port: ${ORACLE_PORT_MSP}
      service: ${ORACLE_SERVICE_MSP}
      user: ${ORACLE_USER_MSP}
      password: ${ORACLE_PASSWORD_MSP}
      instant_client_dir: ${ORACLE_INSTANT_CLIENT_DIR_MSP}
    query: SELECT * FROM HCUE_SEGNOMINAL.VM_CONTROLES_NINOS_GESTANTES
    params: {}

transformations:
  enabled: false

loads:
  - name: cedulados_msp_to_postgres
    source: cedulados_msp
    target: postgresql
    config:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      database: ${POSTGRES_DATABASE}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      truncate_before_load: "true"
    table: cedulados_prueba_msp
    mode: insert

logging:
  level: INFO
  file: logs/digercic_etl_cedulados.log
